"""
AkashSetu - Pydantic Data Models
Defines all data structures for drones, zones, events, and API payloads.
"""

from pydantic import BaseModel, Field
from typing import Optional, List, Dict
from enum import Enum
import uuid
import time


class DroneStatus(str, Enum):
    IDLE = "idle"
    IN_FLIGHT = "in_flight"
    REROUTING = "rerouting"
    LANDING = "landing"
    LANDED = "landed"
    EMERGENCY = "emergency"


class ZoneType(str, Enum):
    RED = "red"         # No-fly zone - strictly prohibited
    YELLOW = "yellow"   # Caution / Restricted / Safety buffer
    GREEN = "green"     # Unrestricted fly zone
    VIRTUAL = "virtual" # Merged dynamic obstacle envelope


class EventType(str, Enum):
    COLLISION_WARNING = "collision_warning"
    COLLISION_AVERTED = "collision_averted"
    SAFETY_BUFFER_ENTERED = "safety_buffer_entered"
    GEOFENCE_WARNING = "geofence_warning"
    GEOFENCE_VIOLATION = "geofence_violation"
    REROUTE = "reroute"
    ALTITUDE_CHANGE = "altitude_change"
    SPEED_CHANGE = "speed_change"
    DRONE_ADDED = "drone_added"
    DRONE_LANDED = "drone_landed"
    SIMULATION_STARTED = "simulation_started"


class Coordinate(BaseModel):
    lat: float
    lng: float


class Waypoint(BaseModel):
    lat: float
    lng: float
    altitude: float = 100.0  # feet


class DroneState(BaseModel):
    """Real-time state of a drone"""
    id: str = Field(default_factory=lambda: f"DRN-{uuid.uuid4().hex[:6].upper()}")
    operator: str = "Unknown"
    operator_color: str = "#00E5FF"
    lat: float = 0.0
    lng: float = 0.0
    altitude: float = 100.0        # feet (30-400)
    speed: float = 50.0            # km/h (30-80)
    heading: float = 0.0           # degrees (0-360)
    source: Coordinate = Field(default_factory=lambda: Coordinate(lat=0, lng=0))
    destination: Coordinate = Field(default_factory=lambda: Coordinate(lat=0, lng=0))
    trajectory: List[Waypoint] = Field(default_factory=list)
    original_trajectory: List[Waypoint] = Field(default_factory=list)
    current_waypoint_idx: int = 0
    status: DroneStatus = DroneStatus.IDLE
    progress: float = 0.0          # 0.0 to 1.0
    scale: float = 1.0             # visual scale based on altitude
    warning_level: int = 0         # 0=none, 1=caution, 2=warning, 3=critical
    created_at: float = Field(default_factory=time.time)


class RestrictedZone(BaseModel):
    """A restricted airspace zone"""
    id: str
    name: str
    zone_type: ZoneType
    center: Coordinate
    radius_m: float = 0.0          # for circular zones, in meters
    buffer_radius_m: float = 200.0 # 200m safety buffer
    polygon: List[Coordinate] = Field(default_factory=list)  # for polygon zones
    description: str = ""
    max_altitude: float = 0.0      # max allowed altitude in feet (0 = fully restricted)


class VirtualMergedZone(BaseModel):
    """A virtual enclosing circle covering multiple nearby restricted zones"""
    id: str
    name: str
    center: Coordinate
    radius_m: float
    buffer_radius_m: float = 200.0
    child_zone_ids: List[str] = Field(default_factory=list)


class SystemLogEntry(BaseModel):
    """Structured system log entry for high-performance terminal console"""
    id: str = Field(default_factory=lambda: uuid.uuid4().hex[:8])
    timestamp: float = Field(default_factory=time.time)
    level: str = "INFO"            # INFO | CAUTION | WARNING | CRITICAL | SUCCESS
    category: str = "SYSTEM"       # GEOFENCE | CONFLICT | FLIGHT | REROUTE | SYSTEM
    source_drone_id: Optional[str] = None
    target_drone_id: Optional[str] = None
    message: str = ""
    metadata: Dict = Field(default_factory=dict)


class SimulationEvent(BaseModel):
    """An event generated by the simulation"""
    id: str = Field(default_factory=lambda: uuid.uuid4().hex[:8])
    event_type: EventType
    timestamp: float = Field(default_factory=time.time)
    drone_ids: List[str] = Field(default_factory=list)
    message: str = ""
    details: dict = Field(default_factory=dict)
    severity: int = 1  # 1=info, 2=warning, 3=critical


class AddDroneRequest(BaseModel):
    """Request to add a new drone"""
    id: Optional[str] = None
    operator: str = "Custom Operator"
    source_lat: float
    source_lng: float
    dest_lat: float
    dest_lng: float
    altitude: float = 100.0
    speed: float = 50.0


class SimulationStats(BaseModel):
    """Live simulation statistics"""
    active_drones: int = 0
    total_drones: int = 0
    completed_drones: int = 0
    collisions_averted: int = 0
    geofence_violations: int = 0
    safety_reroutes: int = 0
    active_warnings: int = 0
    uptime_seconds: float = 0.0


class TelemetryMessage(BaseModel):
    """WebSocket message containing full state"""
    type: str = "telemetry"
    drones: List[DroneState] = Field(default_factory=list)
    logs: List[SystemLogEntry] = Field(default_factory=list)
    stats: SimulationStats = Field(default_factory=SimulationStats)
    zones: List[RestrictedZone] = Field(default_factory=list)
    virtual_zones: List[VirtualMergedZone] = Field(default_factory=list)
    timestamp: float = Field(default_factory=time.time)
